# Generated by Django 6.0.6 on 2026-06-14 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_type',
            field=models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('snack', 'Перекус'), ('drink', 'Напиток')], max_length=10, verbose_name='Тип приема пищи'),
        ),
        migrations.CreateModel(
            name='DishStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portions', models.IntegerField(default=0, verbose_name='Количество порций')),
                ('prepared_at', models.DateTimeField(auto_now_add=True, verbose_name='Время приготовления')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafeteria.dish', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'Остаток готового блюда',
                'verbose_name_plural': 'Остатки готовых блюд',
            },
        ),
    ]
